<?php
declare(strict_types=1);
session_name('parish_registry'); session_start();
$cfg = file_exists(__DIR__.'/../config.php') ? require __DIR__.'/../config.php' : require __DIR__.'/../config.example.php';
date_default_timezone_set($cfg['timezone']);
function db(): PDO { global $cfg; static $db; return $db ??= new PDO("mysql:host={$cfg['db_host']};dbname={$cfg['db_name']};charset=utf8mb4",$cfg['db_user'],$cfg['db_pass'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]); }
function json(array $data,int $status=200) { http_response_code($status); header('Content-Type: application/json'); echo json_encode($data,JSON_UNESCAPED_UNICODE); exit; }
function input(): array { $d=json_decode(file_get_contents('php://input'),true); return is_array($d)?$d:$_POST; }
function user(): array { if (empty($_SESSION['user'])) json(['error'=>'Authentication required'],401); return $_SESSION['user']; }
function allow(array $roles): array { $u=user(); if(!in_array($u['role'],$roles,true)) json(['error'=>'Forbidden'],403); return $u; }
function clean($v): string { return trim(strip_tags((string)$v)); }
function fields(array $r): array { $map=['sacrament'=>'sacrament_type','firstName'=>'first_name','middleName'=>'middle_name','lastName'=>'last_name','gender'=>'gender','dob'=>'date_of_birth','eventDate'=>'event_date','fatherName'=>'father_name','motherName'=>'mother_maiden_name','spouse'=>'spouse_name','book'=>'book_number','page'=>'page_number','line'=>'line_number','minister'=>'minister_name','sponsors'=>'sponsors','marginNotes'=>'margin_notes']; $out=[]; foreach($map as $a=>$b)$out[$b]=clean($r[$a]??$r[$b]??''); return $out; }
function validate(array $r, bool $database=true): array { $f=fields($r); $e=[]; $types=['Baptism','Communion','Confirmation','Marriage','Death']; if(!in_array($f['sacrament_type'],$types,true))$e[]='Missing Sacrament Type'; if(!$f['first_name']||!$f['last_name'])$e[]='First and last name required'; if(!in_array($f['gender'],['Male','Female'],true))$e[]='Gender must be Male or Female'; foreach(['event_date','book_number','page_number','line_number'] as $x)if(!$f[$x])$e[]="$x is required"; foreach(['date_of_birth','event_date'] as $x)if($f[$x]&&!preg_match('/^\\d{4}-\\d{2}-\\d{2}$/',$f[$x]))$e[]='Invalid Date'; if($f['date_of_birth']&&$f['event_date']&&$f['event_date']<$f['date_of_birth'])$e[]='Invalid Date'; if(in_array($f['sacrament_type'],['Baptism','Communion','Confirmation'],true)){if(!$f['father_name'])$e[]='Missing Father Name';if(!$f['mother_maiden_name'])$e[]='Missing Mother Name';} if($database && !$e){$s=db()->prepare('SELECT id FROM sacramental_records WHERE sacrament_type=? AND book_number=? AND page_number=? AND line_number=?');$s->execute([$f['sacrament_type'],$f['book_number'],$f['page_number'],$f['line_number']]);if($s->fetch())$e[]='Duplicate Entry';} return [$f,array_values(array_unique($e))]; }
function record(int $id): array|false { $s=db()->prepare('SELECT r.id,r.sacrament_type sacrament,r.event_date eventDate,r.book_number book,r.page_number page,r.line_number line,r.minister_name minister,r.sponsors,r.margin_notes marginNotes,p.first_name firstName,p.middle_name middleName,p.last_name lastName,p.gender,p.date_of_birth dob,p.father_name fatherName,p.mother_maiden_name motherName,p.spouse_name spouse FROM sacramental_records r JOIN persons p ON p.id=r.person_id WHERE r.id=?');$s->execute([$id]);return $s->fetch(); }
$path=parse_url($_SERVER['REQUEST_URI'],PHP_URL_PATH); $path=preg_replace('#^.*/api/v1#','',$path); $method=$_SERVER['REQUEST_METHOD'];
if($path==='/auth/login'&&$method==='POST'){ $d=input(); $key=clean($d['username']??''); $s=db()->prepare('SELECT id,full_name,username,role,password_hash FROM staff_users WHERE (username=? OR email=?) AND is_active=1 LIMIT 1');$s->execute([$key,$key]);$u=$s->fetch();if(!$u||!password_verify((string)($d['password']??''),$u['password_hash']))json(['error'=>'Invalid credentials'],401); $_SESSION['user']=['id'=>(int)$u['id'],'full_name'=>$u['full_name'],'username'=>$u['username'],'role'=>$u['role']];json(['data'=>$_SESSION['user']]); }
if($path==='/auth/logout'&&$method==='POST'){session_destroy();json(['data'=>true]);} if($path==='/auth/me'&&$method==='GET')json(['data'=>user()]);
if($path==='/records'&&$method==='GET'){allow(['admin','staff','viewer']);$q='%'.clean($_GET['q']??'').'%';$where=' WHERE (p.first_name LIKE ? OR p.middle_name LIKE ? OR p.last_name LIKE ? OR p.date_of_birth LIKE ? OR r.sacrament_type LIKE ? OR r.book_number LIKE ? OR r.page_number LIKE ? OR r.line_number LIKE ?)';$args=array_fill(0,8,$q); foreach(['sacrament'=>'sacrament_type','dob'=>'date_of_birth','book'=>'book_number','page'=>'page_number','line'=>'line_number'] as $k=>$c)if(!empty($_GET[$k])){$where.=" AND ".(str_starts_with($c,'date_')?'p':'r').".$c=?";$args[]=clean($_GET[$k]);}$page=max(1,(int)($_GET['page_num']??1));$per=min(100,max(1,(int)($_GET['per_page']??25)));$count=db()->prepare('SELECT COUNT(*) FROM sacramental_records r JOIN persons p ON p.id=r.person_id'.$where);$count->execute($args);$s=db()->prepare('SELECT r.id,r.sacrament_type sacrament,r.event_date eventDate,r.book_number book,r.page_number page,r.line_number line,r.minister_name minister,r.sponsors,r.margin_notes marginNotes,p.first_name firstName,p.middle_name middleName,p.last_name lastName,p.gender,p.date_of_birth dob,p.father_name fatherName,p.mother_maiden_name motherName,p.spouse_name spouse FROM sacramental_records r JOIN persons p ON p.id=r.person_id'.$where.' ORDER BY r.event_date DESC LIMIT '.$per.' OFFSET '.(($page-1)*$per));$s->execute($args);json(['data'=>$s->fetchAll(),'meta'=>['total'=>(int)$count->fetchColumn(),'page'=>$page,'per_page'=>$per]]); }
if(preg_match('#^/records/(\\d+)$#',$path,$m)&&$method==='GET'){allow(['admin','staff','viewer']);$r=record((int)$m[1]);$r?json(['data'=>$r]):json(['error'=>'Not found'],404);}
if ($path === '/records' && $method === 'POST') {
  $u = allow(['admin', 'staff']);
  list($f, $errors) = validate(input());
  if ($errors) json(['error' => 'Validation failed', 'errors' => $errors], 422);
  $d = db(); $d->beginTransaction();
  try {
    $p = $d->prepare('SELECT id FROM persons WHERE first_name=? AND last_name=? AND date_of_birth <=> ? LIMIT 1');
    $p->execute([$f['first_name'], $f['last_name'], $f['date_of_birth'] ?: null]); $pid = $p->fetchColumn();
    if (!$pid) {
      $p = $d->prepare('INSERT INTO persons(first_name,middle_name,last_name,gender,date_of_birth,father_name,mother_maiden_name,spouse_name) VALUES(?,?,?,?,?,?,?,?)');
      $p->execute([$f['first_name'], $f['middle_name'] ?: null, $f['last_name'], $f['gender'], $f['date_of_birth'] ?: null, $f['father_name'] ?: null, $f['mother_maiden_name'] ?: null, $f['spouse_name'] ?: null]);
      $pid = $d->lastInsertId();
    }
    $s = $d->prepare('INSERT INTO sacramental_records(person_id,sacrament_type,event_date,book_number,page_number,line_number,minister_name,sponsors,margin_notes,created_by) VALUES(?,?,?,?,?,?,?,?,?,?)');
    $s->execute([$pid, $f['sacrament_type'], $f['event_date'], $f['book_number'], $f['page_number'], $f['line_number'], $f['minister_name'] ?: null, $f['sponsors'] ?: null, $f['margin_notes'] ?: null, $u['id']]);
    $id = (int)$d->lastInsertId(); $d->commit();
    json(['data' => record($id), 'meta' => ['next_book_number' => $f['book_number'], 'next_line_number' => (string)((int)$f['line_number'] + 1), 'dedupe_match' => (bool)$pid]], 201);
  } catch (Throwable $e) { $d->rollBack(); json(['error' => 'Could not save record'], 409); }
}
if(preg_match('#^/records/(\\d+)/issue$#',$path,$m)&&$method==='POST'){ $u=allow(['admin','staff']);$r=record((int)$m[1]);if(!$r)json(['error'=>'Not found'],404);$x=input();$name=clean($x['requestor_name']??'');$purpose=clean($x['purpose']??'');if(!$name||!$purpose)json(['error'=>'Requestor name and purpose are required'],422);$s=db()->prepare('INSERT INTO certificate_issuance_logs(sacramental_record_id,requestor_name,purpose,issued_by) VALUES(?,?,?,?)');$s->execute([$r['id'],$name,$purpose,$u['id']]);json(['data'=>['id'=>(int)db()->lastInsertId(),'sacramental_record_id'=>$r['id'],'requestor_name'=>$name,'purpose'=>$purpose]] ,201); }
if(preg_match('#^/records/(\\d+)/certificate\.pdf$#',$path,$m)&&$method==='GET'){allow(['admin','staff']);$r=record((int)$m[1]);$log=(int)($_GET['log_id']??0);$s=db()->prepare('SELECT l.id FROM certificate_issuance_logs l WHERE l.id=? AND l.sacramental_record_id=?');$s->execute([$log,$r['id']??0]);if(!$r||!$s->fetch())json(['error'=>'Issuance log required'],404);$name=trim($r['firstName'].' '.$r['middleName'].' '.$r['lastName']);$title='Certificate of '.$r['sacrament'];$body=$r['sacrament']==='Marriage'?"This certifies that $name and {$r['spouse']} were joined in Holy Matrimony on {$r['eventDate']}.":($r['sacrament']==='Death'?"This certifies that $name departed this life on {$r['eventDate']} and was given ecclesiastical rites.":"This certifies that $name received the Sacrament of {$r['sacrament']} on {$r['eventDate']}.");$text=function($v){return str_replace(['\\','(',')',"\r","\n"],['\\\\','\\(', '\\)', '', ' '],$v);};$stream='BT /F1 20 Tf 72 740 Td ('.$text('PARISH OF OUR LADY OF THE ASSUMPTION').') Tj 0 -46 Td /F1 18 Tf ('.$text($title).') Tj 0 -55 Td /F1 12 Tf ('.$text($body).') Tj 0 -70 Td ('.$text('Book '.$r['book'].'  Page '.$r['page'].'  Line '.$r['line']).') Tj 0 -120 Td ('.$text('Issued: '.date('F j, Y')).') Tj ET';$pdf="%PDF-1.4\n1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj\n2 0 obj<</Type/Pages/Count 1/Kids[3 0 R]>>endobj\n3 0 obj<</Type/Page/Parent 2 0 R/MediaBox[0 0 612 792]/Resources<</Font<</F1 4 0 R>>>>/Contents 5 0 R>>endobj\n4 0 obj<</Type/Font/Subtype/Type1/BaseFont/Times-Roman>>endobj\n5 0 obj<</Length ".strlen($stream).">>stream\n$stream\nendstream endobj\ntrailer<</Root 1 0 R>>\n%%EOF";header('Content-Type: application/pdf');header('Content-Disposition: inline; filename="certificate-'.$r['id'].'.pdf"');echo $pdf;exit; }
if($path==='/imports'&&$method==='POST'){ $u=allow(['admin','staff']);if(empty($_FILES['file'])||$_FILES['file']['error']!==UPLOAD_ERR_OK||$_FILES['file']['size']>5*1024*1024||!preg_match('/\.csv$/i',$_FILES['file']['name']))json(['error'=>'Upload a CSV no larger than 5MB'],422);$h=fopen($_FILES['file']['tmp_name'],'r');$headers=fgetcsv($h);$rows=[];while(($v=fgetcsv($h))!==false){$raw=array_combine($headers,array_pad($v,count($headers),''));[$f,$e]=validate($raw);$rows[]=['row'=>count($rows)+2,'data'=>$raw,'status'=>$e?'Invalid':'Valid','errors'=>$e];}fclose($h);$d=db();$s=$d->prepare('INSERT INTO import_batches(filename,uploaded_by,total_rows,valid_rows) VALUES(?,?,?,?)');$valid=count(array_filter($rows,fn($x)=>$x['status']==='Valid'));$s->execute([basename($_FILES['file']['name']),$u['id'],count($rows),$valid]);$id=(int)$d->lastInsertId();$s=$d->prepare('INSERT INTO import_staged_rows(batch_id,row_number,payload,validation_errors) VALUES(?,?,?,?)');foreach($rows as $r)$s->execute([$id,$r['row'],json_encode($r['data']),json_encode($r['errors'])]);json(['data'=>['batch_id'=>$id,'rows'=>$rows],'meta'=>['total'=>count($rows),'valid'=>$valid]],201); }
if(preg_match('#^/imports/(\\d+)/commit$#',$path,$m)&&$method==='POST'){ $u=allow(['admin','staff']);$d=db();$b=$d->prepare("SELECT * FROM import_batches WHERE id=? AND status='staged'");$b->execute([(int)$m[1]]);$batch=$b->fetch();if(!$batch)json(['error'=>'Staged batch not found'],404);$rows=$d->prepare('SELECT payload FROM import_staged_rows WHERE batch_id=?');$rows->execute([$batch['id']]);$d->beginTransaction();try{$n=0;foreach($rows as $row){[$f,$e]=validate(json_decode($row['payload'],true));if($e)continue;$p=$d->prepare('SELECT id FROM persons WHERE first_name=? AND last_name=? AND date_of_birth <=> ? LIMIT 1');$p->execute([$f['first_name'],$f['last_name'],$f['date_of_birth']?:null]);$pid=$p->fetchColumn();if(!$pid){$p=$d->prepare('INSERT INTO persons(first_name,middle_name,last_name,gender,date_of_birth,father_name,mother_maiden_name,spouse_name) VALUES(?,?,?,?,?,?,?,?)');$p->execute([$f['first_name'],$f['middle_name']?:null,$f['last_name'],$f['gender'],$f['date_of_birth']?:null,$f['father_name']?:null,$f['mother_maiden_name']?:null,$f['spouse_name']?:null]);$pid=$d->lastInsertId();}$s=$d->prepare("INSERT INTO sacramental_records(person_id,sacrament_type,event_date,book_number,page_number,line_number,minister_name,sponsors,margin_notes,source,created_by) VALUES(?,?,?,?,?,?,?,?,?,'bulk_import',?)");$s->execute([$pid,$f['sacrament_type'],$f['event_date'],$f['book_number'],$f['page_number'],$f['line_number'],$f['minister_name']?:null,$f['sponsors']?:null,$f['margin_notes']?:null,$u['id']]);$n++;}$d->prepare("UPDATE import_batches SET committed_rows=?,status='committed' WHERE id=?")->execute([$n,$batch['id']]);$d->commit();json(['data'=>['committed_rows'=>$n]]);}catch(Throwable $e){$d->rollBack();json(['error'=>'Import commit failed'],409);}}
if(($path==='/imports/template' || preg_match('#^/imports/(\\d+)/template$#',$path))&&$method==='GET'){allow(['admin','staff']);header('Content-Type: text/csv; charset=utf-8');header('Content-Disposition: attachment; filename="parish_bulk_import_template.csv"');readfile(__DIR__.'/../parish_bulk_import_template.csv');exit;}
if(preg_match('#^/imports/(\\d+)$#',$path,$m)&&$method==='DELETE'){allow(['admin','staff']);db()->prepare("UPDATE import_batches SET status='discarded' WHERE id=? AND status='staged'")->execute([(int)$m[1]]);json(['data'=>true]);}
if($path==='/issuance-logs'&&$method==='GET'){allow(['admin','staff','viewer']);$page=max(1,(int)($_GET['page']??1));$per=min(100,max(1,(int)($_GET['per_page']??25)));$where='';$args=[];if(!empty($_GET['sacrament'])){$where=' WHERE r.sacrament_type=?';$args[]=clean($_GET['sacrament']);}$count=db()->prepare('SELECT COUNT(*) FROM certificate_issuance_logs l JOIN sacramental_records r ON r.id=l.sacramental_record_id'.$where);$count->execute($args);$s=db()->prepare('SELECT l.id,l.requestor_name issuedTo,l.purpose,l.issued_at timestamp,u.full_name issuedBy,r.sacrament_type sacrament,CONCAT_WS(\' \',p.first_name,p.middle_name,p.last_name) personName FROM certificate_issuance_logs l JOIN sacramental_records r ON r.id=l.sacramental_record_id JOIN persons p ON p.id=r.person_id JOIN staff_users u ON u.id=l.issued_by'.$where.' ORDER BY l.issued_at DESC LIMIT '.$per.' OFFSET '.(($page-1)*$per));$s->execute($args);json(['data'=>$s->fetchAll(),'meta'=>['total'=>(int)$count->fetchColumn(),'page'=>$page,'per_page'=>$per]]);}
if(!str_starts_with($_SERVER['REQUEST_URI'],'/api/v1')){readfile(__DIR__.'/parish-registry.html');exit;} json(['error'=>'Not found'],404);
