<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\{AuthController,RecordController,IssuanceController,ImportController,SettingsController,CertificateTemplateController,ProfileController,CertificateRequestController,ParishController,StaffAccountController,AdminController};

Route::get('/', fn()=>response()->file(public_path('public-home.html')));
Route::get('/staff', fn()=>response()->file(public_path('parish-registry.html')));
Route::get('/admin', fn()=>response()->file(public_path('admin.html')));
Route::redirect('/certificate-request', '/#request');
Route::redirect('/request-status', '/#request');
Route::prefix('api/v1')->group(function(){
 Route::post('auth/login',[AuthController::class,'login']);
 Route::post('admin/auth/login',[AuthController::class,'adminLogin']);
 Route::post('certificate-requests',[CertificateRequestController::class,'store']);
 Route::get('parishes',[ParishController::class,'index']);
 Route::get('certificate-requests/track',[CertificateRequestController::class,'track']);
 Route::middleware('session-auth')->group(function(){
  Route::post('auth/logout',[AuthController::class,'logout']); Route::get('auth/me',[AuthController::class,'me']);
  Route::middleware('role:admin')->group(function(){Route::get('admin/auth/me',[AuthController::class,'me']);Route::get('admin/overview',[AdminController::class,'overview']);Route::get('admin/parishes',[ParishController::class,'management']);Route::post('admin/parishes',[ParishController::class,'store']);Route::put('admin/parishes/{parish}',[ParishController::class,'update']);Route::get('admin/staff-accounts',[StaffAccountController::class,'index']);Route::post('admin/staff-accounts',[StaffAccountController::class,'store']);Route::put('admin/staff-accounts/{user}',[StaffAccountController::class,'update']);Route::put('admin/staff-accounts/{user}/password',[StaffAccountController::class,'resetPassword']);Route::get('admin/activity',[AdminController::class,'activity']);Route::get('admin/system',[AdminController::class,'system']);});
 Route::middleware('role:staff')->group(function(){Route::get('records',[RecordController::class,'index']);Route::get('records/{record}',[RecordController::class,'show']);Route::get('issuance-logs',[IssuanceController::class,'index']);Route::get('certificate-requests',[CertificateRequestController::class,'index']);Route::get('certificate-requests/{certificateRequest}',[CertificateRequestController::class,'show']);Route::put('certificate-requests/{certificateRequest}',[CertificateRequestController::class,'update']);Route::get('certificate-requests/{certificateRequest}/matches',[CertificateRequestController::class,'matches']);Route::get('certificate-requests/{certificateRequest}/attachment',[CertificateRequestController::class,'attachment']);Route::get('certificate-requests/{certificateRequest}/claim-slip.pdf',[CertificateRequestController::class,'claimSlip']);Route::post('certificate-requests/{certificateRequest}/issue',[CertificateRequestController::class,'issue']);Route::post('records',[RecordController::class,'store']);Route::post('records/{record}/issue',[IssuanceController::class,'store']);Route::get('records/{record}/certificate.pdf',[IssuanceController::class,'certificate']);Route::post('imports',[ImportController::class,'store']);Route::post('imports/{batch}/commit',[ImportController::class,'commit']);Route::delete('imports/{batch}',[ImportController::class,'destroy']);Route::get('imports/template',[ImportController::class,'template']);Route::get('settings',[SettingsController::class,'show']);Route::put('settings',[SettingsController::class,'update']);Route::post('settings/logo',[SettingsController::class,'uploadLogo']);Route::post('settings/seal',[SettingsController::class,'uploadSeal']);Route::post('settings/priest-signature',[SettingsController::class,'uploadSignature']);Route::put('certificate-templates/{sacrament}',[CertificateTemplateController::class,'update']);Route::get('settings/image/{type}',[SettingsController::class,'image']);Route::get('certificate-preview-settings',[SettingsController::class,'preview']);Route::get('certificate-preview-image/{type}',[SettingsController::class,'image']);});
  Route::middleware('role:staff')->group(function(){Route::get('parish-management',[ParishController::class,'management']);Route::post('parishes',[ParishController::class,'store']);Route::put('parishes/{parish}',[ParishController::class,'update']);Route::get('staff-accounts',[StaffAccountController::class,'index']);Route::post('staff-accounts',[StaffAccountController::class,'store']);Route::put('staff-accounts/{user}',[StaffAccountController::class,'update']);});
  Route::put('me',[ProfileController::class,'update']);Route::put('me/password',[ProfileController::class,'updatePassword']);Route::post('me/avatar',[ProfileController::class,'uploadAvatar']);Route::get('me/avatar',[ProfileController::class,'avatar']);
 });
});
