<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
return new class extends Migration { public function up():void {
if(!Schema::hasTable('staff_users'))Schema::create('staff_users',fn(Blueprint $t)=>$t->increments('id')&&$t->string('full_name',150)&&$t->string('username',80)->unique()&&$t->string('email',150)->nullable()->unique()&&$t->string('avatar_path',255)->nullable()&&$t->string('password_hash',255)&&$t->enum('role',['admin','staff','viewer'])->default('staff')&&$t->boolean('is_active')->default(true)&&$t->timestamps());
if(!Schema::hasTable('persons'))Schema::create('persons',function(Blueprint $t){$t->increments('id');$t->string('first_name',100);$t->string('middle_name',100)->nullable();$t->string('last_name',100);$t->enum('gender',['Male','Female']);$t->date('date_of_birth')->nullable();$t->string('father_name',200)->nullable();$t->string('mother_maiden_name',200)->nullable();$t->string('spouse_name',200)->nullable();$t->timestamps();$t->index(['last_name','first_name']);$t->index('date_of_birth');});
if(!Schema::hasTable('sacramental_records'))Schema::create('sacramental_records',function(Blueprint $t){$t->increments('id');$t->unsignedInteger('person_id');$t->enum('sacrament_type',['Baptism','Communion','Confirmation','Marriage','Death']);$t->date('event_date');$t->string('book_number',20);$t->string('page_number',20);$t->string('line_number',20);$t->string('minister_name',200)->nullable();$t->text('sponsors')->nullable();$t->text('margin_notes')->nullable();$t->enum('source',['manual_entry','bulk_import'])->default('manual_entry');$t->unsignedInteger('created_by')->nullable();$t->timestamps();$t->foreign('person_id')->references('id')->on('persons')->cascadeOnDelete();$t->foreign('created_by')->references('id')->on('staff_users')->nullOnDelete();$t->unique(['sacrament_type','book_number','page_number','line_number']);$t->index('sacrament_type');$t->index('event_date');});
if(!Schema::hasTable('certificate_issuance_logs'))Schema::create('certificate_issuance_logs',function(Blueprint $t){$t->increments('id');$t->unsignedInteger('sacramental_record_id');$t->string('requestor_name',200);$t->string('purpose',150);$t->unsignedInteger('issued_by');$t->timestamp('issued_at')->useCurrent();$t->string('pdf_path',255)->nullable();$t->foreign('sacramental_record_id')->references('id')->on('sacramental_records')->restrictOnDelete();$t->foreign('issued_by')->references('id')->on('staff_users')->restrictOnDelete();$t->index('issued_at');});
if(!Schema::hasTable('import_batches'))Schema::create('import_batches',function(Blueprint $t){$t->increments('id');$t->string('filename');$t->unsignedInteger('uploaded_by');$t->unsignedInteger('total_rows');$t->unsignedInteger('valid_rows');$t->unsignedInteger('committed_rows')->default(0);$t->enum('status',['staged','committed','discarded'])->default('staged');$t->timestamp('uploaded_at')->useCurrent();$t->foreign('uploaded_by')->references('id')->on('staff_users')->restrictOnDelete();});
if(!Schema::hasTable('import_staged_rows'))Schema::create('import_staged_rows',function(Blueprint $t){$t->increments('id');$t->unsignedInteger('batch_id');$t->unsignedInteger('row_number');$t->json('payload');$t->json('validation_errors');$t->foreign('batch_id')->references('id')->on('import_batches')->cascadeOnDelete();});
if(!Schema::hasTable('parish_settings'))Schema::create('parish_settings',function(Blueprint $t){$t->tinyInteger('id')->unsigned()->primary();$t->string('parish_name',200)->default('Parish of Our Lady of the Assumption');$t->string('diocese_name',200)->default('Diocese of San Ildefonso');$t->string('address',255)->default('');$t->string('seal_image_path',255)->nullable();$t->string('default_priest_name',200)->default('');$t->string('priest_signature_path',255)->nullable();$t->timestamp('updated_at')->useCurrent()->useCurrentOnUpdate();});
if(!Schema::hasTable('certificate_templates'))Schema::create('certificate_templates',function(Blueprint $t){$t->enum('sacrament_type',['Baptism','Communion','Confirmation','Marriage','Death'])->primary();$t->string('title_text',150);$t->text('body_template');$t->string('footer_note',255)->default('Not valid without the parish dry seal.');$t->timestamp('updated_at')->useCurrent()->useCurrentOnUpdate();});
} public function down():void{} };
