<html><head><style>@page { size: letter; margin: 1in .85in; } body { font-family:'Times New Roman',serif;margin:0; }</style></head><body>
<p style="text-align:center;font-size:12px;letter-spacing:1.5px;color:#7a2734;margin:0;">{{ $parish->diocese_name }}</p>
<p style="text-align:center;font-size:28px;font-weight:bold;color:#101010;margin:8px 0 4px;">{{ $parish->parish_name }}</p>
<p style="text-align:center;font-size:12px;color:#4a4a4a;margin:0 0 26px;">{{ $parish->address }}</p><div style="border-top:2px solid #a9812f;margin-bottom:34px;"></div>
<div style="text-align:center;margin-bottom:34px;">@if($sealDataUri)<img src="{{ $sealDataUri }}" style="display:block;width:110px;height:110px;margin:0 auto;object-fit:contain;" alt="Parish seal"/>@else<div style="width:102px;height:102px;border-radius:50%;background:#a9812f;border:4px solid #8a6a24;margin:0 auto;display:table;"><div style="display:table-cell;vertical-align:middle;text-align:center;color:#3a2c0c;font-size:12px;font-weight:bold;line-height:1.4;">PARISH<br/>SEAL</div></div>@endif</div>
<p style="text-align:center;font-size:23px;font-weight:bold;letter-spacing:.75px;color:#101010;margin:0 0 34px;">{{ $title }}</p><p style="font-size:16px;line-height:2.1;text-align:justify;color:#161616;margin:0 0 36px;">{!! $body !!}</p>
<table width="100%" style="border-top:1px solid #d8d2c2;border-bottom:1px solid #d8d2c2;margin-bottom:34px;"><tr><td style="padding:16px 12px;font-size:13px;"><span style="display:block;font-size:11px;color:#4a4a4a;">Book No.</span><strong>{{ $record->book_number }}</strong></td><td style="padding:16px 12px;font-size:13px;"><span style="display:block;font-size:11px;color:#4a4a4a;">Page No.</span><strong>{{ $record->page_number }}</strong></td><td style="padding:16px 12px;font-size:13px;"><span style="display:block;font-size:11px;color:#4a4a4a;">Line Entry No.</span><strong>{{ $record->line_number }}</strong></td></tr></table>
@if($record->margin_notes)<table width="100%" style="margin:0 0 30px;"><tr><td style="background:#f3e0e3;border-left:4px solid #7a2734;padding:14px 18px;"><span style="display:block;font-size:12px;font-weight:bold;color:#5e1f29;">CANONICAL MARGIN NOTES</span><span style="color:#3a1015;font-size:14px;">{{ $record->margin_notes }}</span></td></tr></table>@endif
<table width="100%" style="margin-top:50px;"><tr><td width="50%" style="vertical-align:bottom;">@if($signatureDataUri)<img src="{{ $signatureDataUri }}" style="height:44px;margin-bottom:6px;" alt="Priest signature"/>@endif<div style="border-top:1px solid #101010;width:210px;margin-bottom:8px;"></div><strong style="font-size:14px;">{{ $priestName }}</strong><br/><span style="font-size:12px;color:#4a4a4a;">Officiating Priest / Parish Priest</span></td><td width="50%" align="right" style="vertical-align:bottom;"><div style="border-top:1px solid #101010;width:170px;margin-bottom:8px;margin-left:auto;"></div><span style="font-size:12px;color:#4a4a4a;">Date Issued</span><br/><strong style="font-size:14px;">{{ $today }}</strong></td></tr></table>
<p style="text-align:center;font-size:12px;color:#4a4a4a;border-top:1px dashed #c3cbd9;padding-top:18px;margin-top:50px;">Issued to <strong>{{ $issuedTo }}</strong> for the purpose of <strong>{{ $purpose }}</strong>. {{ $footerNote }}</p></body></html>
